[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "scistree2"     
dynamic = ["version"]     
description = "Large-scale Inference of Cell Lineage Trees and Genotype Calling from Noisy Single-Cell Data Using Efficient Local Search"
readme = "README.md" 
requires-python = ">=3.6" 
license = { text = "GPL3" }
authors = [
    { name = "Haotian Zhang", email = "haotianzh@uconn.edu" },
    { name = "Yufeng Wu", email = "yufeng.wu@uconn.edu" }
]
keywords = ["cell lineage tree", "fast inference"]

dependencies = [
    "numpy",
    "pandas",
    "pptree"
]

[tool.setuptools.dynamic]
version = {attr = "scistree2.__version__"}

[project.urls]
Homepage = "https://github.com/yufengwudcs/ScisTree2"
"Bug Tracker" = "https://github.com/yufengwudcs/ScisTree2/issues"
