name: Build and Publish

on:
  release:
    types: [published]
  workflow_dispatch:


jobs:
  build_sdist:
    name: Build Source Distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install build tools
        run: pip install build
      - name: Build sdist
        run: python -m build --sdist
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup MSVC (Windows)
        uses: ilammy/msvc-dev-cmd@v1
        if: runner.os == 'Windows'

      - name: DEBUG - Check pyproject.toml
        shell: bash
        run: |
          echo "=== CONTENTS OF pyproject.toml ==="
          cat pyproject.toml
          echo "=================================="

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.19.0
        env:
          # Only keep the skip directive here if you want
          # ALL other config should come from pyproject.toml
          CIBW_SKIP: "*-win32 pp*"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  publish_to_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/scistree2/
    permissions:
      id-token: write
    
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1